name: Release
on:
  push:
    tags:
      - "v*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        release_tag: ${{ github.ref }}
        overwrite: true 
        # ldflags: -extldflags -static -X github.com/chrislusf/seaweedfs/weed/util.COMMIT=${{github.sha}}
